#!/usr/bin/env python

# pip-audit-bulk: run pip-audit in bulk, saving (reduced) reports in JSON

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

# This entire script is path-sensitive.
_HERE = Path(__file__).resolve().parent

_REQUIREMENTS = _HERE / "requirements"
assert _REQUIREMENTS.is_dir(), "missing requirements to audit (wrong dir?)"

_OUT = _HERE / "audits"
_OUT.mkdir(exist_ok=True)

_FAILURES = _HERE / "failures"
_FAILURES.unlink(missing_ok=True)

_SKIPPED = _HERE / "skipped"
_SKIPPED.unlink(missing_ok=True)

_SUMMARY_RESULTS = {
    "success": [],
    "failure": [],
}
_SUMMARY_SUCCESS_TEMPLATE = """
| `{name}` | {vuln_count} |
"""
_SUMMARY_FAILURE_TEMPLATE = """
`{name}` failed with:

```console
{stderr}
```
"""
_SUMMARY = Path(os.environ["GITHUB_STEP_SUMMARY"])

assert shutil.which("osv-scanner"), "missing osv-scanner"

# First pass: actually run the audits.
for req in sorted(_REQUIREMENTS.glob("*.txt")):
    print(f"[+] auditing: {req.name}", file=sys.stderr)
    result = subprocess.run(
        [
            "osv-scanner",
            "--lockfile",
            f"requirements.txt:{req}",
            "--format=json",
            f"--config=osv-scanner-config.toml",
        ],
        capture_output=True,
        text=True,
    )

    # If we don't see anything on stdout, pip-audit probably failed.
    # Log it as an error.
    if not result.stdout:
        print(f"\t>:( pip-audit failed: {result.stderr}")
        with _FAILURES.open(mode="at") as failures:
            print(req.name, file=failures)
        _SUMMARY_RESULTS["failure"].append((req.name, result.stderr))
        continue

    # Reduce the audit to only dependencies that include vulnerabilities
    audit = json.loads(result.stdout)
    results = audit["results"]

    # If we're left with anything, dump it as a result.
    out = _OUT / req.with_suffix(".audit.json").name
    vuln_count = 0
    if results:
        assert len(results) == 1
        vulns = results[0]["packages"]
        vuln_count = len(vulns)
        print(
            f"\t:-( found {vuln_count} vulnerabilities in {req.name}",
            file=sys.stderr,
        )
        out.write_text(json.dumps(vulns, indent=2))
    else:
        out.unlink(missing_ok=True)
        print(f"\t:-) no vulnerabilities found in {req.name}", file=sys.stderr)

    _SUMMARY_RESULTS["success"].append((req.name, vuln_count))


# Second pass: clean up any audits that don't have corresponding
# requirement files, from a previous run of this script.
# This is nasty, and should probably go somewhere else.
for audit in _OUT.glob("*.json"):
    req = _REQUIREMENTS / audit.with_suffix("").with_suffix(".txt").name
    if not req.is_file():
        print(f":-O {audit.name} orphaned ({req.name}), deleting")
        audit.unlink()


success_render = ""
for name, vuln_count in _SUMMARY_RESULTS["success"]:
    success_render += _SUMMARY_SUCCESS_TEMPLATE(name=name, vuln_count=vuln_count)


failure_render = ""
for name, stderr in _SUMMARY_RESULTS["failure"]:
    failure_render += _SUMMARY_FAILURE_TEMPLATE.format(name=name, stderr=stderr)

render = f"""
The following audits completed successfully:

| Input | Vulnerabilities found |
| ----- | --------------------- |
{success_render}


The following audits failed, and should be manually inspected:

{failure_render}
"""

with _SUMMARY.open(mode="a") as io:
    print(render, file=io)
